export const FETCH_TVS_REQUESTS = 'FETCH_TVS_REQUESTS';
export const FETCH_TVS_SUCCESS = 'FETCH_TVS_SUCCESS';
export const FETCH_TVS_ERROR = 'FETCH_TVS_ERROR';
export const FETCH_TVS_BY_ID_REQUESTS = 'FETCH_TVS_BY_ID_REQUESTS';
export const FETCH_TVS_BY_ID_SUCCESS = 'FETCH_TVS_BY_ID_SUCCESS';
export const FETCH_TVS_BY_ID_ERROR = 'FETCH_TVS_BY_ID_ERROR';